[package]
name = "option-entry"
version = "0.1.0"
edition = "2024"
publish = true
repository = "https://github.com/parrrate/option-entry"
authors = ["Alisa Feistel <alisafeistel@gmail.com>"]
license = "MIT OR Apache-2.0"
rust-version = "1.90"
description = "`Entry` for `Option`"
exclude = ["/.github", "/.gitignore", "/.vscode", "CHANGELOG.md"]

[dependencies]

[features]
unstable = []
